Use echo instead of print

diff --git a/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main b/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main
--- a/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main
+++ b/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main
@@ -4,7 +4,7 @@ set -euo pipefail
 ACME_JSON="$1"
 
 if ! cert=$(jq -ec ".${CERT_RESOLVER}.Certificates[] | select(.domain.main == \"${MAIN_DOMAIN}\")" <"$ACME_JSON"); then
-    print -u 2 "Could not find certificate for CERT_RESOLVER=$CERT_RESOLVER and MAIN_DOMAIN=$MAIN_DOMAIN @ $ACME_JSON"
+    echo "Could not find certificate for CERT_RESOLVER=$CERT_RESOLVER and MAIN_DOMAIN=$MAIN_DOMAIN @ $ACME_JSON" >&2
     exit 0
 fi
 
diff --git a/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/run b/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/run
--- a/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/run
+++ b/root/etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/run
@@ -1,22 +1,22 @@
 #!/usr/bin/with-contenv bash
 
 if [[ -z "${CERT_RESOLVER:-}" ]]; then
-    print -u 2 "CERT_RESOLVER not set"
+    echo "CERT_RESOLVER not set" >&2
     exit 1
 elif [[ -z "${MAIN_DOMAIN:-}" ]]; then
-    print -u 2 "MAIN_DOMAIN not set"
+    echo "MAIN_DOMAIN not set" >&2
     exit 1
 elif [[ -z "${CERT_DIR:-}" ]] || [[ ! -d $CERT_DIR ]]; then
-    print -u 2 "CERT_DIR not set or not found"
+    echo "CERT_DIR not set or not found" >&2
     exit 1
 elif [[ -z "${OUTPUT_DIR:-}" ]] || [[ ! -d $OUTPUT_DIR ]]; then
-    print -u 2 "OUTPUT_DIR not set or not found"
+    echo "OUTPUT_DIR not set or not found" >&2
     exit 1
 fi
 
 if ! find "$CERT_DIR" -type f -name '*.json' -exec /etc/s6-overlay/s6-rc.d/svc-mod-zncfik-mod/main '{}' \;
 then
-    print -u 2 "Initial cert extraction failed"
+    echo "Initial cert extraction failed" >&2
     exit 1
 fi
 
